CREATE TABLE TB_DIRETORIOS(
  ID SERIAL PRIMARY KEY,
  NOME VARCHAR(255) not null,
  PARENT_ID INT,
  CONSTRAINT FK_DIRETORIO_PARENT FOREIGN KEY (PARENT_ID) REFERENCES TB_DIRETORIOS(ID)
);

CREATE TABLE TB_ARQUIVOS(
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) not null,
    DIRETORIO_ID INT,
    CONSTRAINT FK_ARQUIVO_DIRETORIO FOREIGN KEY (DIRETORIO_ID) REFERENCES TB_DIRETORIOS(ID)
);